name: nkust_ap
description: A new Flutter application.

version: 3.8.16+30816

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ap_common: ^0.19.4
  ap_common_firebase: ^0.12.0
  ap_common_plugin: ^0.3.0
  #official plugin
  http: ^0.13.3
  html: ^0.15.0
  http_parser: ^4.0.0
  #third party plugin
  dio: ^4.0.0
  dio_http_cache:
    git:
      url: https://github.com/hurshi/dio-http-cache
  tuple: ^2.0.0
  sprintf: ^6.0.0
  image: ^3.0.2
  extended_image: ^4.1.0
  flutter_inappwebview: ^5.3.2
  google_sign_in_dartio:
    git:
      url: https://github.com/GroovinChip/firebase_dart_sdk
      path: google_sign_in_dart
      ref: null_safety
  tflite:
    git:
      url: https://github.com/TreeHD/flutter_tflite
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter


#dependency_overrides:
#  ap_common:
#    path: ../ap_common
#  ap_common_firebase:
#    path: ../../GitHub/ap_common_firebase
#  ap_common_plugin:
#    path: ../../GitHub/ap_common_plugin

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/leave_campus_data.json
    - assets/schedule_data.json
    - changelog.json
    - assets/webap_captcha.tflite
    - assets/labels.txt
